# a="sudipto mandal"
# b="SudIpto MandAL"
# d="SUDIPTO MANDAL"
# e="sudIPTO mAnDaL"
# print(a)
# print(b)
# print(a.title())
# print(b.title())
# print(b.upper())
# print(b.lower())
# c=a.replace("sudipto","hori")
# print(c)
# print(a.swapcase())
# print(d.swapcase())
# print(e.swapcase())
# print(a.count('a'))


a="good morning Rahim,how are you ?"
user_input=input("Enter your name:")
print("good morning {},how are you?{}".format(user_input,"HI"))
