import turtle
t=turtle.Turtle()
turtle.setup(600)
t.penup()
t.backward(100)
t.fillcolor("pink")
t.pendown()
t.begin_fill()
for i in range(2):
    t.forward(200)
    t.left(90)
    t.forward(200)
    t.left(90)
t.end_fill()
turtle.mainloop()